name: Build binary file

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Dwnload AutoHotKey v2.0-rc archive
      shell: pwsh
      run: |
        # Special thank: nekocodeX/GitHub-Action-Ahk2Exe
        Write-Output "TEMP=$env:TEMP; LOCALAPPDATA=$env:LOCALAPPDATA"
        $GetLatestAhk2ExeUrl = $(Invoke-WebRequest "https://api.github.com/repos/AutoHotkey/Ahk2Exe/releases/latest" | ConvertFrom-Json).assets[0].browser_download_url
        Invoke-WebRequest "https://www.autohotkey.com/download/ahk-v2.zip" -OutFile "$env:TEMP\autohotkey.zip"
        Invoke-WebRequest "$GetLatestAhk2ExeUrl" -OutFile "$env:TEMP\ahk2exe.zip"

    - name: Install AutoHotKey v2.0-rc
      shell: pwsh
      run: |
        # Special thank: nekocodeX/GitHub-Action-Ahk2Exe
        Expand-Archive -Path "$env:TEMP\autohotkey.zip" -DestinationPath "$env:LOCALAPPDATA\Programs\AutoHotkey" -Force
        Expand-Archive -Path "$env:TEMP\ahk2exe.zip" -DestinationPath "$env:LOCALAPPDATA\Programs\AutoHotkey\Compiler" -Force
        Remove-Item -Path "$env:TEMP\autohotkey.zip" -Force
        Remove-Item -Path "$env:TEMP\ahk2exe.zip" -Force
        Write-Output ("$env:LOCALAPPDATA\Programs\AutoHotkey;" + "$env:LOCALAPPDATA\Programs\AutoHotkey\Compiler") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build x64 binary file
      shell: pwsh
      run: |
        ahk2exe.exe /in AutoWeMeeting.ahk /out AutoWeMeeting64.exe /base $env:LOCALAPPDATA\Programs\AutoHotkey\AutoHotkey64.exe

    - name: Build x32 binary file
      shell: pwsh
      run: |
        ahk2exe.exe /in AutoWeMeeting.ahk /out AutoWeMeeting32.exe /base $env:LOCALAPPDATA\Programs\AutoHotkey\AutoHotkey32.exe

    - name: Zip file
      shell: pwsh
      run: |
        $CompressRelease = @{
            LiteralPath= "AutoWeMeeting64.exe", "AutoWeMeeting32.exe", "AutoWeMeeting.ahk", "AWM-JoinMeet.png", "README.md", "LICENSE"
            CompressionLevel = "Optimal"
            DestinationPath = "AutoHotKey.zip"
        }
        Compress-Archive @CompressRelease

    - name: Upload artifact to workflows
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: AutoHotKey.zip


    - name: Create and upload artifact to Releases
      uses: softprops/action-gh-release@v1
      with:
        name: AutoWeMeeting Build ID${{ github.run_number }}
        tag_name: Build-${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        files: AutoHotKey.zip
